name: example_drift_export_column_check_bug
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  drift: ^2.20.2
  drift_dev: ^2.20.3

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.12
  test: ^1.25.8
